#!/bin/bash
# Clear nftables rules generated by this project.

set -u

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

NFT_BIN="${NFT_BIN:-/usr/sbin/nft}"

if [ ! -x "$NFT_BIN" ]; then
    if command -v nft >/dev/null 2>&1; then
        NFT_BIN="$(command -v nft)"
    else
        echo "nft command not found"
        exit 1
    fi
fi

delete_table() {
    family="$1"
    table="$2"

    if "$NFT_BIN" list table "$family" "$table" >/dev/null 2>&1; then
        "$NFT_BIN" delete table "$family" "$table"
        echo "Deleted table $family $table"
    else
        echo "Table $family $table not found, skipped"
    fi
}

echo "Stopping and disabling nat.service to prevent rules from being recreated..."
systemctl stop nat 2>/dev/null || true
systemctl disable nat 2>/dev/null || true

delete_table ip self-nat
delete_table ip6 self-nat
delete_table ip self-filter
delete_table ip6 self-filter

rm -f /etc/nftables-nat/nat-diy.nft
rm -f /etc/nftables-nat/nat-prepare.nft

echo ""
echo "All nftables rules generated by nat have been removed."
echo "nat.service has been stopped and disabled."
echo "Installed files and config are kept."
echo "Run the install or switch command again to apply /etc/nat.conf and re-enable startup."
