# 简化单端口转发：本地端口:远程IP或域名:远程端口
10000:baidu.com:443
# 仍兼容老格式 SINGLE
SINGLE,10001,443,baidu.com,tcp
# 测试 RANGE
RANGE,1000,2000,baidu.com
# 测试 localhost
SINGLE,12345,22,localhost
REDIRECT,7123-7234,2222,tcp
DROP,input,src_ip=8.8.8.8/24,dst_port=443
