#!/bin/bash
# Uninstall nat service and remove nftables rules generated by this project.

set -u

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

NFT_BIN="${NFT_BIN:-/usr/sbin/nft}"
if [ ! -x "$NFT_BIN" ] && command -v nft >/dev/null 2>&1; then
    NFT_BIN="$(command -v nft)"
fi

delete_table() {
    family="$1"
    table="$2"

    if [ -x "$NFT_BIN" ] && "$NFT_BIN" list table "$family" "$table" >/dev/null 2>&1; then
        "$NFT_BIN" delete table "$family" "$table"
        echo "Deleted table $family $table"
    else
        echo "Table $family $table not found, skipped"
    fi
}

echo "Stopping and disabling nat.service..."
systemctl stop nat 2>/dev/null || true
systemctl disable nat 2>/dev/null || true

delete_table ip self-nat
delete_table ip6 self-nat
delete_table ip self-filter
delete_table ip6 self-filter

echo "Removing service and program files..."
rm -f /lib/systemd/system/nat.service
rm -f /etc/systemd/system/nat.service
rm -f /usr/local/bin/nat
rm -f /etc/nftables-nat/nat-diy.nft
rm -f /etc/nftables-nat/nat-prepare.nft
rmdir /etc/nftables-nat 2>/dev/null || true
rm -rf /opt/nat

systemctl daemon-reload
systemctl reset-failed nat 2>/dev/null || true

if [ "${REMOVE_NAT_CONFIG:-0}" = "1" ]; then
    rm -f /etc/nat.conf /etc/nat.toml /etc/nat_example.conf /etc/nat_example.toml
    echo "Config files removed."
else
    echo "Config files are kept:"
    echo "  /etc/nat.conf"
    echo "  /etc/nat.toml"
    echo "  /etc/nat_example.conf"
    echo "  /etc/nat_example.toml"
    echo "Run with REMOVE_NAT_CONFIG=1 if you also want to remove config files."
fi

echo ""
echo "nat service has been uninstalled."
